/**
 * Generates prisma/seed.sql from the shared demo data in seed-data.ts, so the
 * SQL-editor seed path stays in sync with the Prisma seed. Run offline (no DB):
 *   npx tsx prisma/gen-seed-sql.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import * as data from "./seed-data";

const PID = data.BKDS_JUNE_PERIOD_ID;

function sqlValue(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  return `'${String(v).replace(/'/g, "''")}'`;
}

/** DELETE then INSERT the child rows of a table for a given period. */
function childBlock(
  table: string,
  rows: Record<string, unknown>[],
  periodId: string = PID,
): string {
  if (rows.length === 0) return "";
  // Child `id` columns default to cuid() at the Prisma layer, which does not
  // exist in raw SQL — so emit an explicit, deterministic id per row.
  const withPid = rows.map((r, i) => ({
    id: `${table}_${periodId}_${i}`,
    periodId,
    ...r,
  }));
  const columns: string[] = [];
  for (const row of withPid) {
    for (const key of Object.keys(row)) {
      if (!columns.includes(key)) columns.push(key);
    }
  }
  const colList = columns.map((c) => `"${c}"`).join(", ");
  const values = withPid
    .map(
      (row) =>
        `  (${columns.map((c) => sqlValue((row as Record<string, unknown>)[c])).join(", ")})`,
    )
    .join(",\n");
  return [
    `DELETE FROM "${table}" WHERE "periodId" = '${periodId}';`,
    `INSERT INTO "${table}" (${colList}) VALUES`,
    `${values};`,
    "",
  ].join("\n");
}

const out: string[] = [];
out.push(
  "-- Generated by prisma/gen-seed-sql.ts — do not edit by hand.",
  "-- Seeds the 3 properties + one demo ReportPeriod (BKDS, June 2026).",
  "-- Idempotent: properties upsert on code; the demo period's children are cleared and re-inserted.",
  "",
);

// Properties (upsert on code)
out.push("-- Properties");
for (const p of data.properties) {
  out.push(
    `INSERT INTO "properties" ("id","code","name","restaurantName","spaName","roomCount","area","createdAt","updatedAt") VALUES`,
    `  (${sqlValue(p.id)}, ${sqlValue(p.code)}, ${sqlValue(p.name)}, ${sqlValue(p.restaurantName)}, ${sqlValue(p.spaName)}, ${sqlValue(p.roomCount)}, ${sqlValue(p.area)}, now(), now())`,
    `ON CONFLICT ("code") DO UPDATE SET "name"=EXCLUDED."name", "restaurantName"=EXCLUDED."restaurantName", "spaName"=EXCLUDED."spaName", "roomCount"=EXCLUDED."roomCount", "area"=EXCLUDED."area", "updatedAt"=now();`,
    "",
  );
}

// Demo report period (upsert on propertyId+period)
out.push(
  "-- Demo report period: BKDS June 2026",
  `INSERT INTO "report_periods" ("id","propertyId","period","status","createdAt","updatedAt") VALUES`,
  `  (${sqlValue(PID)}, ${sqlValue(data.BKDS_ID)}, ${sqlValue(data.BKDS_JUNE_PERIOD)}, 'FINAL', now(), now())`,
  `ON CONFLICT ("propertyId","period") DO UPDATE SET "status"=EXCLUDED."status", "updatedAt"=now();`,
  "",
);

// Child sections
out.push(childBlock("revenue_summaries", data.revenueSummaries));
out.push(childBlock("segment_production", data.segmentProduction));
out.push(childBlock("room_type_production", data.roomTypeProduction));
out.push(childBlock("nationality_production", data.nationalityProduction));
out.push(childBlock("length_of_stay", data.lengthOfStay));
out.push(childBlock("account_production", data.accountProduction));
out.push(childBlock("ads_performance", data.adsPerformance));
out.push(childBlock("fnb_sales", data.fnbSales));
out.push(childBlock("fnb_source_of_booking", data.fnbSources));
out.push(childBlock("fnb_acquisition", data.fnbAcquisition));
out.push(childBlock("chope_reports", [data.chopeReport]));
out.push(childBlock("gokai_reports", data.gokaiReports));
out.push(childBlock("spa_sales", data.spaSales));
out.push(childBlock("spa_treatments", data.spaTreatments));
out.push(childBlock("platform_rankings", data.platformRankings));
out.push(childBlock("tripadvisor_metrics", data.tripadvisorMetrics));
out.push(childBlock("social_media_metrics", data.socialMediaMetrics));
out.push(childBlock("booking_pace", data.bookingPace));
out.push(childBlock("forecasts", data.forecasts));
out.push(childBlock("narrative_content", data.narrativeContent));
out.push(childBlock("influencer_collabs", data.influencerCollabs));

// Real June 2026 periods for BKDU and BKV (executive summary + market segment)
for (const extra of data.extraPeriods) {
  out.push(
    `-- Real report period: ${extra.propertyId} ${extra.period}`,
    `INSERT INTO "report_periods" ("id","propertyId","period","status","createdAt","updatedAt") VALUES`,
    `  ('${extra.periodId}', '${extra.propertyId}', '${extra.period}', 'FINAL', now(), now())`,
    `ON CONFLICT ("propertyId","period") DO UPDATE SET "status"=EXCLUDED."status", "updatedAt"=now();`,
    "",
  );
  out.push(childBlock("revenue_summaries", extra.revenueSummaries, extra.periodId));
  out.push(childBlock("segment_production", extra.segmentProduction, extra.periodId));
}

const target = join(__dirname, "seed.sql");
writeFileSync(target, out.join("\n"));
console.log(`Wrote ${target}`);
